### ISSUE TITLE
First-class support for systems of equations

### ISSUE THREAD

**Issue by StevenClontz** [StevenClontz/masterit#1]

**Comment by StevenClontz** [comment]
@siwelwerd has a solution for `masterit-tbil-la` -- maybe worth bringing upstream?

**Comment by siwelwerd** [comment]
See https://github.com/StevenClontz/masterit-tbil-la/blob/51ba26fa5d0998b469d46463097da49c1f68cffb/__common__.sage#L115

It takes a matrix as an argument, because that's what we always have handy in linear algebra. Not sure how general you want to go here.

Also PreTeXt is really finicky with these, so right now the PreText code has to look like
`    <md alignment="alignat">
                <xsl:attribute name="alignat-columns"><xsl:value-of select="alignCols"/></xsl:attribute>
              <xsl:for-each select="system/*">
                <mrow><xsl:value-of select="."/></mrow>
              </xsl:for-each>
    </md>`

I am wondering if the better way is to have the template not be purely valid PreText, but allow for a tag like
`<system><xsl:value-of select="system-name"></system>`. But I think this would require writing a pretext.xsl file to handle the <system> and turn it into valid PreTeXt (as above).

**Comment by StevenClontz** [comment]
I think the most portable solution is to rig up something that works inside LaTeX displaymath mode, e.g. `\[ \begin{foo}...\end{foo} \]`, just like a matrix is `\[\begin{matrix}...\end{matrix}\]`. Then we'd simply represent it as `<me><xsl:value-of select="system"/></me>`, which is valid PreTeXt.

Perhaps a matrix that doesn't have brackets could be used? `\begin{matrix} x & + & y & = & 1 \\ ... \end{matrix}`

**Comment by StevenClontz** [comment]
Closed in 41a2e576fc0cf83e97d1f5e2bba6482192bfe97d -- I gave @siwelwerd coauthor credit as it was modified from masterit-tbil-la/__common__.sage.

The system is built as a matrix, so usage is simple: `<me><xsl:value-of select="system"/></me>`.

Drew - you could exchange your custom Sage object's `_latex_` method to call this function.

**Comment by StevenClontz** [comment]
Place for improvement: reduce spacing between columns (in a way that works locally, in LaTeX, MathJaX, CodeCogs, etc.).
